export const styles = {
	container: "space-y-4",
	loadingList: "space-y-6",
	skeletonItem: "p-4 rounded-xl bg-muted/30 space-y-3 animate-fade-up",
	skeletonRow: "flex items-center justify-between",
	skeletonLeft: "flex items-center gap-3",
	skeletonTextGroup: "space-y-2",
	errorRoot: "flex items-center gap-3 p-4 rounded-xl bg-destructive/10 text-destructive",
	errorText: "text-sm",
	emptyRoot: "flex flex-col items-center justify-center py-12 text-center",
	emptyIconWrapper: "p-4 rounded-2xl bg-muted/50 mb-4",
	emptyTitle: "text-muted-foreground font-medium mb-1",
	emptySubtitle: "text-sm text-muted-foreground/70",
	card: "p-4 rounded-xl border transition-all duration-300 bg-card hover:bg-muted/30 animate-fade-up",
	cardHeader: "flex items-start justify-between gap-4 mb-4",
	cardLeft: "flex items-center gap-3 min-w-0",
	iconWrapper: "p-2.5 rounded-xl flex-shrink-0",
	iconWrapperHigh: "bg-red-500/10",
	iconWrapperMedium: "bg-yellow-500/10",
	iconWrapperLow: "bg-green-500/10",
	iconHigh: "h-5 w-5 text-red-500",
	iconMedium: "h-5 w-5 text-yellow-500",
	iconLow: "h-5 w-5 text-green-500",
	title: "font-semibold truncate",
	daysLeftRow: "flex items-center gap-1.5 mt-1",
	daysLeftText: "text-xs text-muted-foreground",
	badge: "flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-semibold",
	badgeComplete: "bg-green-500/10 text-green-600",
	badgeIncomplete: "bg-muted",
	progressBar: "h-2",
} as const;
