export const styles = {
	sheetContent: "sm:max-w-[425px]",
	formBody: "space-y-4 py-4",
	titleRow: "relative",
	titleInputRow: "flex gap-2",
	titleInputWrapper: "flex-1 flex items-center gap-2",
	emojiPickerWrapper: "absolute top-full left-0 z-50 mt-1",
	tabsList: "grid w-full grid-cols-2",
	tabsContent: "space-y-4",
	durationRow: "flex gap-2 items-center mt-1",
	durationInput: "flex-1",
	durationUnit: "text-sm text-muted-foreground",
	quickAddRow: "flex gap-2 mt-2",
	timeGrid: "grid grid-cols-2 gap-4",
	addMoreSection: "flex items-center justify-between py-2 border-t",
	addMoreLabel: "space-y-0.5",
	addMoreHint: "text-xs text-muted-foreground",
	footer: "pt-4 border-t",
	errorText: "text-sm text-destructive",
} as const;
