export const styles = {
	sheetContent: "sm:max-w-[500px]",
	titleRow: "flex items-center gap-2",
	titleText: "flex-1 text-xl",
	emoji: "mr-2 text-2xl",
	badge: "text-xs",
	descriptionRow: "flex items-center gap-2 text-base",
	contentBody: "space-y-6 py-6",
	sectionHeader: "flex items-center gap-2 text-sm font-medium text-muted-foreground",
	sectionContent: "pl-6 space-y-2",
	sectionContentSingle: "pl-6",
	row: "flex justify-between items-center",
	rowLabel: "text-sm text-muted-foreground",
	rowValue: "text-base font-semibold",
	durationValue: "text-lg font-bold text-primary",
	notesContent: "pl-6",
	notesText: "text-sm leading-relaxed whitespace-pre-wrap bg-muted p-4 rounded-lg",
	footer: "flex-col sm:flex-row gap-2",
	footerButton: "w-full sm:w-auto",
} as const;
