export const styles = {
  root: "flex flex-col md:flex-row gap-6",
  calendarWrapper: "md:w-1/2 flex justify-center",
  calendar: "rounded-xl border bg-card p-4",
  detailsColumn: "md:w-1/2",
  emptyState: "flex flex-col items-center justify-center h-full p-8 border rounded-xl bg-muted/30",
  emptyStateIcon: "p-3 rounded-full bg-muted/50 mb-3",
  emptyStateText: "text-muted-foreground",
  cardContentLoading: "p-5 space-y-4",
  cardContentError: "p-5 flex items-center justify-center",
  cardContent: "p-5",
  contentInner: "space-y-5",
  header: "flex justify-between items-start gap-3",
  headerTitle: "text-lg font-semibold mb-2",
  badge: "gap-1.5",
  addButton: "gap-1.5",
  sectionTitle: "text-sm font-medium flex items-center gap-2 mb-3",
  iconWrapperPrimary: "p-1.5 rounded-lg bg-primary/10",
  iconWrapperDestructive: "p-1.5 rounded-lg bg-destructive/10",
  taskList: "space-y-2",
  taskItem: "flex items-center gap-3 p-3 rounded-xl transition-colors",
  milestoneList: "space-y-2",
  milestoneItem: "flex items-center gap-3 p-3 rounded-xl bg-destructive/5 border border-destructive/10",
  emptyList: "flex items-center justify-center py-6 rounded-xl bg-muted/20",
  emptyListText: "text-sm text-muted-foreground",
  errorWrapper: "flex items-center gap-2 text-destructive",
  errorText: "text-sm",
} as const;
