export const styles = {
	container: "space-y-1.5",
	skeletonContainer: "space-y-3",
	skeletonItem: "flex items-center gap-3 py-3 px-3 rounded-xl bg-muted/30 animate-fade-up",
	errorState: "flex items-center gap-2 p-4 rounded-xl bg-destructive/5 text-destructive",
	emptyState: "flex flex-col items-center justify-center py-8 text-center",
	emptyIcon: "p-3 rounded-full bg-muted/50 mb-3",
	emptyText: "text-sm text-muted-foreground",
	toggleError: "flex items-center gap-2 p-2 rounded-lg bg-destructive/5 text-destructive mb-2",
	taskItem: "flex items-start gap-3 text-sm py-3 px-3 rounded-xl transition-all duration-200 hover:bg-muted/50 cursor-pointer animate-fade-up",
	taskContent: "flex flex-col flex-grow truncate",
	taskTitle: "font-medium text-foreground truncate",
	taskTitleCompleted: "font-medium line-through text-muted-foreground truncate",
	taskSubtext: "text-[10px] text-muted-foreground mt-0.5",
	iconWrapper: "w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5",
	viewAllLink: "flex items-center justify-center gap-2 text-sm text-muted-foreground hover:text-primary text-center py-3 rounded-xl hover:bg-muted/30 transition-colors mt-2",
} as const;
