export const styles = {
  root: "min-h-[288px]",
  header: "flex justify-between items-center py-2 px-1",
  monthTitle: "text-lg font-semibold",
  daysGrid: "grid grid-cols-7 gap-1 text-center text-sm font-medium text-muted-foreground",
  dayLabel: "py-1",
  cellsGrid: "grid grid-cols-7 gap-1 min-h-[288px]",
  loadingGrid: "grid grid-cols-7 gap-1 min-h-[288px] items-center justify-center",
  loader: "h-8 w-8 animate-spin text-primary col-span-7 mx-auto my-auto",
  cell: "p-1.5 border rounded-md h-10 flex items-center justify-center transition-colors",
  cellCurrentMonth: "cursor-pointer hover:bg-accent dark:hover:bg-accent/50",
  cellOtherMonth: "text-muted-foreground/30 bg-muted/10 dark:bg-muted/5",
  cellToday: "bg-primary/10 border-primary/50 dark:bg-primary/20 dark:border-primary/70 font-semibold",
  errorMessage: "text-sm text-red-600 text-center py-2",
  modalOverlay: "fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4",
  modalCard: "rounded-xl shadow-lg w-full mx-auto",
  moodButtons: "flex justify-around gap-3 sm:gap-4 mb-6",
  moodButton: "h-16 w-16 sm:h-20 sm:w-20 rounded-full",
  moodButtonWrapper: "relative flex items-center justify-center",
  cancelArea: "flex justify-center pt-4",
} as const;
