export const styles = {
	card: "border shadow-sm transition-all duration-200 h-[380px] flex flex-col overflow-hidden",
	cardHighlighted: "ring-2 scale-[1.01]",
	cardFiltered: "col-span-full h-[calc(100vh-200px)]",
	cardHeader: "pb-3 pt-4 px-4 border-b border-border/50",
	headerRow: "flex items-center justify-between",
	headerLeft: "flex items-center gap-2.5",
	title: "font-semibold text-sm",
	subtitle: "text-xs text-muted-foreground",
	headerActions: "flex items-center gap-1.5",
	badge: "bg-background/80 text-foreground border-0 text-xs px-2 py-0.5",
	cardContent: "p-0 flex-1 min-h-0 overflow-hidden",
	taskList: "space-y-2 p-3 h-full overflow-y-auto",
	emptyState: "flex flex-col items-center justify-center h-full text-center",
	emptyIcon: "h-10 w-10 text-muted-foreground/30 mb-2",
	emptyText: "text-sm text-muted-foreground font-medium",
	emptySubtitle: "text-xs text-muted-foreground/60",
	listBottomPad: "h-24",
} as const;
